import System.IO

getSitePrecontentHtml :: String
getSitePrecontentHtml = 
    "<!DOCTYPE html>\n" ++
    "<html>\n" ++
    "<head>\n" ++
    "   <meta charset=\"UTF-8\">\n" ++
    "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" ++
    "   <title>Haskell-Generated Site</title>\n" ++
    "   <style>\n" ++
    "       body {\n" ++
    "           background-color: #aaa;\n" ++
    "           font-family: sans-serif;\n" ++
    "           padding-left: 1rem;\n" ++
    "       }\n" ++
    "   </style>\n" ++
    "</head>\n" ++
    "<body>\n"

getSitePostcontentHtml :: String
getSitePostcontentHtml = 
    "</body>\n" ++
    "</html>\n"

getIntroHtml :: String
getIntroHtml = 
    "<h1>Haskell-Generated Site</h1>\n" ++
    "<p>This site was generated by <a target=\"_blank\" href=\"https://github.com/edwardtanguay/et021-haskell-basics/blob/dev/haskgen.hs\">this Haskell script</a>.</p>\n" ++ 
    "<p>See also <a target=\"_blank\" href=\"https://tanguay-eu.vercel.app/forays/263\">my notes</a> on this project.</p>\n" ++
    "<hr/>\n"

getTitleHtml :: String -> String
getTitleHtml title = 
    "<h2>" ++ title ++ "</h2>\n"

getListHtml :: String -> [String] -> String
getListHtml title strings = 
    getTitleHtml title ++
    "<ul>\n" ++ concatMap (\s -> "<li>" ++ s ++ "</li>\n") strings ++ "</ul>\n"

getFooterHtml :: String -> String
getFooterHtml version = 
    "<hr/>\n" ++
    "<p>version: " ++ version ++ "</p>\n" ++
    "See also: Edward's <a href=\"https://tanguay-eu.vercel.app/howtos\">Howtos</a> and <a href=\"https://tanguay-eu.vercel.app/forays\">Forays</a>\n"
    

main :: IO ()
main = do
    let filePath = "/var/www/haskell/index.html"
    let list1_html = getListHtml "Example: create UL/LI list from list" ["one", "two", "three", "four", "five", "six"]
    let footer_html = getFooterHtml "0.5"
    let html = getSitePrecontentHtml ++ getIntroHtml ++ list1_html ++ footer_html ++ getSitePostcontentHtml
    writeFile filePath html
