import System.IO

getSitePrecontentHtml :: String
getSitePrecontentHtml = 
    "<!DOCTYPE html>" ++
    "<html>" ++
    "<head>" ++
    "   <meta charset=\"UTF-8\">" ++
    "   <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" ++
    "   <title>Haskell-Generated Site</title>" ++
    "   <style>" ++
    "       body {" ++
    "           background-color: #aaa;" ++
    "           font-family: sans-serif;" ++
    "           padding-left: 1rem;" ++
    "       }" ++
    "   </style>" ++
    "</head>" ++
    "<body>"

getSitePostcontentHtml :: String
getSitePostcontentHtml = 
    "</body>" ++
    "</html>"

getIntroHtml :: String
getIntroHtml = 
    "<h1>Haskell-Generated Site</h1>\n" ++
    "<p>This site was generated by <a target=\"_blank\" href=\"https://github.com/edwardtanguay/et021-haskell-basics/blob/dev/haskgen.hs\">this Haskell script</a>.</p>" ++ 
    "<p>See also <a target=\"_blank\" href=\"https://tanguay-eu.vercel.app/forays/263\">my notes</a> on this project." ++
    "<hr/>"

getTitleHtml :: String -> String
getTitleHtml title = 
    "<h2>" ++ title ++ "</h2>"

getListHtml :: String -> [String] -> String
getListHtml title strings = 
    getTitleHtml title ++
    "<ul>\n" ++ concatMap (\s -> "<li>" ++ s ++ "</li>\n") strings ++ "</ul>"

main :: IO ()
main = do
    let filePath = "/var/www/haskell/index.html"
    let list1_html = getListHtml "Example: create UL/LI list from list" ["one", "two", "three", "four", "five", "six"]
    let version = "0.3"
    let html = getSitePrecontentHtml ++ getIntroHtml ++ list1_html ++ "</p><hr/><p>version: " ++ version  ++ "</p>" ++ getSitePostcontentHtml
    writeFile filePath html
